#!/bin/bash

# @file write_monit_restart_diags
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2013  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

# Called by monit to gather extra diags from chronos before it is restarted due
# to being unresponsive.

PIDFILE=/var/run/chronos.pid
DIAGS_DIR=/var/log/chronos/monit_restart_diags

# Ensure the extra diags directory exists.
[ -e "$DIAGS_DIR" ] || mkdir $DIAGS_DIR

# Gather the diagnostics we want:
# -  What the PID file things the chronos PID is.
# -  What chronos processes are actually running.
# -  What sockets chronos has open.
# -  Whether it's responding to pings.
cat $PIDFILE                       > $DIAGS_DIR/pidfile
ps -eaf                            > $DIAGS_DIR/processes.log
netstat -plan                      > $DIAGS_DIR/netstat.log 2>&1
curl --verbose --silent --max-time 1 http://localhost:7253/ping > $DIAGS_DIR/ping.log 2>&1

:
